# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    crv.doctrine_entity_repository.user:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\User
    crv.doctrine_entity_repository.lock:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Lock
    crv.doctrine_entity_repository.key:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Key
    crv.doctrine_entity_repository.employee:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Employee
    crv.doctrine_entity_repository.lockkey:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Lockkey
    crv.doctrine_entity_repository.employeekey:
        class: Doctrine\ORM\EntityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - AppBundle\Entity\Employeekey
    app.jwt_token_authenticator:
            parent: lexik_jwt_authentication.security.guard.jwt_token_authenticator
            class: AppBundle\Security\Guard\JWTAuthenticator
          
